// <auto-generated />
using App.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220302115953_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("App.Domain.Entities.VmtCounty", b =>
                {
                    b.Property<long>("BaselineJanVmt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountyFips")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountyName")
                        .HasColumnType("TEXT");

                    b.Property<long>("CountyVmt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateAtLow")
                        .HasColumnType("TEXT");

                    b.Property<double>("Mean7CountyVmt")
                        .HasColumnType("REAL");

                    b.Property<double>("Mean7CountyVmtAtLow")
                        .HasColumnType("REAL");

                    b.Property<double>("Mean7PercentChangeFromJan")
                        .HasColumnType("REAL");

                    b.Property<double>("PercentChangeFromJan")
                        .HasColumnType("REAL");

                    b.Property<double>("PercentChangeFromLow")
                        .HasColumnType("REAL");

                    b.Property<string>("StateName")
                        .HasColumnType("TEXT");

                    b.ToTable("VmtCounties");
                });
#pragma warning restore 612, 618
        }
    }
}
